apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keel
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.keel.sh
    chart: keel
    targetRevision: '1.0.3'
    helm:
      parameters:
        - name: helmProvider.enabled
          value: 'false'
  destination:
    namespace: keel
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true